CREATE TABLE IF NOT EXISTS SPRINGVUE.USER (
  ID INT NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(6) NOT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  CREATED DATETIME(6) NOT NULL,
  PRIMARY KEY (ID))
ENGINE = InnoDB;